INSERT INTO Artistes (Artistes_ID, Nom, Genre, Nb_Membres) VALUES
(1, 'Henry PLC', 'Classical', 10),
(2, 'Morrison Ltd', 'Blues', 10),
(3, 'Mcdonald-Merritt', 'Electronic', 6),
(4, 'Esparza LLC', 'Metal', 7),
(5, 'Copeland and Sons', 'Classical', 8),
(6, 'Shah Group', 'Rap', 5),
(7, 'Harris, Salazar and Charles', 'Rap', 7),
(8, 'Ryan LLC', 'Jazz', 8),
(9, 'Dominguez-Dodson', 'Hip-hop', 5),
(10, 'Mendoza-Murphy', 'Metal', 5),
(11, 'Kelly and Sons', 'KPop', 6),
(12, 'Gallegos Group', 'Rock', 3),
(13, 'Walton-Wilcox', 'Classical', 9),
(14, 'Ashley-Chaney', 'Jazz', 9),
(15, 'Cole, Miller and Collins', 'KPop', 4),
(16, 'Hunter, Frazier and Castillo', 'Electronic', 8),
(17, 'Newton-Stewart', 'Rap', 6),
(18, 'Herman, Shannon and Donaldson', 'Electronic', 8),
(19, 'Schmidt-Mercado', 'Hip-hop', 10),
(20, 'Mcdonald, Garza and Taylor', 'Electronic', 10),
(21, 'Meyer Ltd', 'Hip-hop', 9),
(22, 'Smith, Brown and Schaefer', 'Metal', 9),
(23, 'Coleman, Andersen and Murray', 'Classical', 3),
(24, 'Pierce, Miranda and Hodges', 'Hip-hop', 10),
(25, 'Harris LLC', 'Rap', 5),
(26, 'Freeman PLC', 'Jazz', 9),
(27, 'Kennedy-Flynn', 'Electronic', 7),
(28, 'Carey-Cain', 'KPop', 7),
(29, 'Patterson and Sons', 'Country', 6),
(30, 'Fox, Perez and Ray', 'Rap', 9),
(31, 'Mooney Inc', 'Metal', 10),
(32, 'Daniels-Banks', 'Rap', 5),
(33, 'Russell-Steele', 'Metal', 6),
(34, 'Ford, Ortiz and Ramos', 'Blues', 8),
(35, 'Weeks and Sons', 'Rock', 7),
(36, 'Chapman-Ferguson', 'Jazz', 3),
(37, 'Scott Group', 'Rock', 9),
(38, 'Swanson-Davis', 'Electronic', 6),
(39, 'Woodard-Smith', 'Electronic', 10),
(40, 'Cuevas, Moore and Newton', 'Metal', 4),
(41, 'Berger Group', 'Jazz', 8),
(42, 'Garcia Inc', 'Electronic', 3),
(43, 'Sanchez, Garcia and Rogers', 'Electronic', 9),
(44, 'Cuevas, Martinez and Porter', 'Country', 6),
(45, 'Nielsen-Mercado', 'Rock', 6),
(46, 'Smith Ltd', 'Rock', 9),
(47, 'Baker, Simmons and Johnson', 'Blues', 10),
(48, 'Walker Group', 'Metal', 7),
(49, 'Allen-Thompson', 'Jazz', 4),
(50, 'Arias-Carter', 'Metal', 6),
(51, 'Palmer LLC', 'KPop', 8),
(52, 'Chavez LLC', 'Classical', 9),
(53, 'Cabrera and Sons', 'Jazz', 9),
(54, 'Erickson, Maldonado and Mcdaniel', 'Rap', 7),
(55, 'Ramirez-Mckee', 'Rock', 9),
(56, 'Smith Inc', 'Rock', 5),
(57, 'Hill-Foster', 'Rap', 4),
(58, 'Butler-Espinoza', 'Rock', 8),
(59, 'Johnson Ltd', 'Electronic', 3),
(60, 'Williams, Smith and Anderson', 'Electronic', 6),
(61, 'Johns, Wells and Riddle', 'Rock', 9),
(62, 'Burton-Evans', 'Rap', 9),
(63, 'White, Johnston and Mendoza', 'Rock', 7),
(64, 'Simmons Group', 'Country', 7),
(65, 'Burton, Miller and Gamble', 'Electronic', 9),
(66, 'Ryan-Medina', 'Jazz', 7),
(67, 'Guerrero Group', 'Blues', 8),
(68, 'Jenkins, Ortega and Cannon', 'Rock', 3),
(69, 'Durham Group', 'Hip-hop', 8),
(70, 'Smith-Gibson', 'Country', 6),
(71, 'Pruitt, Morgan and Patel', 'Rap', 4),
(72, 'Bradshaw-Alexander', 'Rock', 9),
(73, 'Yu Ltd', 'Classical', 4),
(74, 'Johnson-Shea', 'Classical', 4),
(75, 'Carlson-Brown', 'Electronic', 9),
(76, 'Friedman-Sullivan', 'Metal', 9),
(77, 'Hebert-White', 'Classical', 5),
(78, 'Tate, Stephenson and Perkins', 'Rap', 6),
(79, 'Kelley, Moore and Alvarez', 'Classical', 10),
(80, 'Bowman, Rosales and Solis', 'Classical', 9),
(81, 'Knapp, Ramirez and Li', 'Jazz', 9),
(82, 'Higgins LLC', 'Blues', 9),
(83, 'Randolph LLC', 'Blues', 3),
(84, 'Hurst-Browning', 'Country', 8),
(85, 'Ramirez-Wade', 'Rap', 4),
(86, 'Johnson and Sons', 'Jazz', 5),
(87, 'Peters-Lawson', 'Blues', 4),
(88, 'Daniels Inc', 'KPop', 8),
(89, 'Davis Group', 'Electronic', 3),
(90, 'Williams, Crawford and Campbell', 'Electronic', 6),
(91, 'Hanson, Jones and Webster', 'Metal', 6),
(92, 'Williams LLC', 'Jazz', 9),
(93, 'Gonzalez, Robertson and Oconnor', 'Blues', 9),
(94, 'Lane, Zavala and Williams', 'Rap', 5),
(95, 'Finley Ltd', 'Rap', 5),
(96, 'Mueller, Mack and Wright', 'Metal', 7),
(97, 'Cruz-Torres', 'Rock', 8),
(98, 'Richardson, Davis and Ford', 'Classical', 5),
(99, 'Crawford, Ryan and Vasquez', 'Hip-hop', 10),
(100, 'Gonzalez-Miller', 'Classical', 10);
