INSERT INTO Artistes (Artistes_ID, Nom, Genre, Nb_Membres) VALUES
(1, 'Giles-Johnson', 'Electronic', 5),
(2, 'Murray Inc', 'Metal', 3),
(3, 'Miller-Thomas', 'Country', 5),
(4, 'Garcia-Ortiz', 'Metal', 6),
(5, 'Gould, Smith and Torres', 'Blues', 3),
(6, 'Hogan LLC', 'Classical', 10),
(7, 'Pace-Jimenez', 'Classical', 4),
(8, 'Scott, Johnson and Richards', 'Country', 6),
(9, 'Mccarthy, Grant and Elliott', 'Hip-hop', 5),
(10, 'Suarez Ltd', 'Rap', 4),
(11, 'Bell-Galloway', 'Hip-hop', 8),
(12, 'Kelly, Baker and Jones', 'Rock', 4),
(13, 'Daugherty LLC', 'Jazz', 5),
(14, 'Barrera-Garcia', 'Classical', 6),
(15, 'Dean-Leonard', 'Rock', 6),
(16, 'Simpson and Sons', 'Jazz', 4),
(17, 'Greene, Erickson and Harris', 'Jazz', 7),
(18, 'Smith-Norton', 'Electronic', 6),
(19, 'Watkins, Castro and Taylor', 'Blues', 4),
(20, 'Hampton, Campbell and Miller', 'Rap', 4),
(21, 'Garcia Inc', 'Rap', 4),
(22, 'Ball-Moran', 'Electronic', 7),
(23, 'Nunez-Garcia', 'KPop', 8),
(24, 'Walker-Moran', 'Metal', 10),
(25, 'Raymond LLC', 'Rock', 10),
(26, 'Stevens, Payne and Holloway', 'KPop', 8),
(27, 'Harris, Armstrong and Scott', 'Rap', 7),
(28, 'Weaver-Benton', 'Country', 9),
(29, 'Johnson PLC', 'Metal', 5),
(30, 'Castro, Morgan and Smith', 'Rock', 5),
(31, 'Pham, Johnson and Soto', 'Blues', 7),
(32, 'Rice Ltd', 'Hip-hop', 3),
(33, 'Walker, Love and Cox', 'Rap', 10),
(34, 'Smith LLC', 'KPop', 5),
(35, 'Hopkins, Hayes and Cox', 'Classical', 10),
(36, 'Pugh, Kim and Morris', 'Rap', 10),
(37, 'Bruce-Morris', 'Hip-hop', 5),
(38, 'Chan-Turner', 'Rock', 10),
(39, 'Rose, Orozco and Hall', 'Metal', 4),
(40, 'Jimenez, Aguirre and Gilbert', 'Country', 10),
(41, 'Santiago LLC', 'Rap', 10),
(42, 'Love-Roberson', 'Classical', 7),
(43, 'Griffin-Phillips', 'Blues', 4),
(44, 'Johnson, Wolfe and Stein', 'Jazz', 8),
(45, 'Roberts-Wong', 'Rock', 8),
(46, 'Buchanan-Hall', 'Blues', 10),
(47, 'Harrington and Sons', 'Hip-hop', 10),
(48, 'Avila-Kelly', 'Hip-hop', 4),
(49, 'Bell, Lewis and Harvey', 'Rap', 9),
(50, 'Black PLC', 'Hip-hop', 10),
(51, 'Cruz Inc', 'Metal', 10),
(52, 'Lopez, Ford and Hampton', 'Rock', 6),
(53, 'Perry, Gonzalez and Lee', 'Rock', 5),
(54, 'Powers-Perry', 'Rock', 8),
(55, 'Simon, Montgomery and Phillips', 'Rock', 3),
(56, 'Chen, Matthews and Pruitt', 'KPop', 9),
(57, 'Johnson-Smith', 'Jazz', 8),
(58, 'Munoz and Sons', 'KPop', 7),
(59, 'Espinoza-Price', 'Jazz', 6),
(60, 'Johnson, Key and Mercado', 'Classical', 7),
(61, 'Roth-Ross', 'Metal', 8),
(62, 'Henderson, Odom and Clark', 'Classical', 3),
(63, 'Weaver, Ross and Rivera', 'KPop', 9),
(64, 'Ortiz and Sons', 'KPop', 9),
(65, 'Crawford, Nelson and Wells', 'Hip-hop', 5),
(66, 'Andrews-Houston', 'Electronic', 10),
(67, 'Ingram and Sons', 'Hip-hop', 7),
(68, 'Owen, Evans and Wise', 'Jazz', 4),
(69, 'Singh Group', 'Metal', 9),
(70, 'Adkins-Acevedo', 'Classical', 9),
(71, 'Watkins Inc', 'Metal', 10),
(72, 'Wagner, Davis and Thomas', 'Classical', 7),
(73, 'Weber, Kelly and Berry', 'Blues', 8),
(74, 'Travis-Mayo', 'Rap', 9),
(75, 'Martin-Pham', 'Classical', 3),
(76, 'Reynolds Inc', 'KPop', 6),
(77, 'Johns, Baker and Kim', 'KPop', 7),
(78, 'Butler and Sons', 'Hip-hop', 5),
(79, 'Archer, Manning and Simmons', 'Jazz', 9),
(80, 'Alvarez and Sons', 'Metal', 10),
(81, 'Cardenas PLC', 'Classical', 9),
(82, 'Smith, Price and Hill', 'Country', 6),
(83, 'Todd, Lee and Hernandez', 'Blues', 4),
(84, 'Williams, Jackson and Wheeler', 'Rap', 3),
(85, 'Price PLC', 'Hip-hop', 4),
(86, 'Harvey, Hernandez and Richardson', 'Rap', 6),
(87, 'Guerrero-Alexander', 'KPop', 7),
(88, 'Adams-Ryan', 'Classical', 6),
(89, 'Booth Inc', 'Rock', 6),
(90, 'Watson-Schneider', 'Rock', 8),
(91, 'Galloway Group', 'Rock', 4),
(92, 'Gibbs, James and White', 'Metal', 7),
(93, 'Santos-Frank', 'Electronic', 9),
(94, 'Edwards-Ayers', 'Hip-hop', 7),
(95, 'Martin, Ali and Harris', 'Electronic', 5),
(96, 'Mueller PLC', 'Electronic', 8),
(97, 'Jimenez Group', 'Rap', 5),
(98, 'Casey, Reynolds and Jones', 'KPop', 3),
(99, 'Cole-Stewart', 'Blues', 9),
(100, 'Murphy and Sons', 'Rock', 10)
