INSERT INTO Artistes (Artistes_ID, Nom, Genre, Nb_Membres) VALUES
(1, 'Knight-Huffman', 'KPop', 4),
(2, 'Fischer Group', 'Classical', 7),
(3, 'Martin, Lewis and Peterson', 'Rap', 10),
(4, 'Joyce-Smith', 'Metal', 4),
(5, 'Stevens, Anthony and Robinson', 'Country', 4),
(6, 'Flowers-Butler', 'Blues', 6),
(7, 'Howard-Jones', 'Jazz', 5),
(8, 'Dickerson, Wilson and Martin', 'Hip-hop', 3),
(9, 'Lewis Ltd', 'Electronic', 5),
(10, 'Martin, Flowers and Henry', 'Rock', 4),
(11, 'Garrison Group', 'Jazz', 7),
(12, 'Miller-Johnson', 'Classical', 3),
(13, 'Thomas, Wheeler and Jones', 'Country', 3),
(14, 'Hernandez LLC', 'Country', 4),
(15, 'Martinez LLC', 'Country', 3),
(16, 'Bryan Group', 'Rock', 4),
(17, 'Castillo-Stokes', 'Jazz', 9),
(18, 'Gibson LLC', 'Country', 6),
(19, 'Miller-Gilbert', 'Country', 6),
(20, 'Rose PLC', 'Electronic', 6),
(21, 'Gill-Cuevas', 'Jazz', 10),
(22, 'Freeman-Hanson', 'Blues', 10),
(23, 'Simmons, Leonard and Evans', 'Metal', 6),
(24, 'Barnes, Ballard and Gonzales', 'Rock', 6),
(25, 'Vincent-Benitez', 'Metal', 6),
(26, 'Weaver-Rojas', 'Rock', 10),
(27, 'Willis, Williams and Carter', 'Rap', 3),
(28, 'Dunn, Barnes and King', 'Rap', 10),
(29, 'Martinez-Fuller', 'Rap', 4),
(30, 'Scott-Walker', 'Jazz', 8),
(31, 'Garcia-Johnson', 'Rap', 5),
(32, 'Jennings-Parrish', 'Metal', 10),
(33, 'Obrien and Sons', 'Rock', 4),
(34, 'Browning, Herrera and Rowe', 'Rock', 5),
(35, 'Porter, Moore and Mccoy', 'Blues', 5),
(36, 'Brown, Baker and Conner', 'Blues', 3),
(37, 'Gibson and Sons', 'KPop', 5),
(38, 'Calhoun-Harvey', 'KPop', 7),
(39, 'Boone LLC', 'Electronic', 7),
(40, 'Ward-Joseph', 'Hip-hop', 4),
(41, 'Briggs Ltd', 'Country', 6),
(42, 'Rodriguez and Sons', 'Rock', 3),
(43, 'May, Martin and West', 'Rap', 7),
(44, 'Spencer, Cardenas and Williamson', 'Hip-hop', 8),
(45, 'Rosales-Brown', 'Rap', 3),
(46, 'Smith, Jones and Anderson', 'Rap', 5),
(47, 'Roberts-Gibson', 'Rock', 10),
(48, 'Mendoza-Smith', 'Jazz', 7),
(49, 'Payne-Oconnell', 'Metal', 3),
(50, 'Taylor Inc', 'Classical', 10),
(51, 'Ibarra LLC', 'KPop', 5),
(52, 'Foster, Keith and Long', 'Country', 8),
(53, 'Chase, White and Blair', 'Blues', 5),
(54, 'Fowler, Preston and Sanchez', 'KPop', 9),
(55, 'Gonzales, Knight and Rojas', 'Blues', 10),
(56, 'Graves PLC', 'Electronic', 3),
(57, 'Jones-West', 'Hip-hop', 3),
(58, 'Moreno, Pham and Gamble', 'Jazz', 5),
(59, 'Travis Inc', 'Rap', 8),
(60, 'Jones, Sharp and Moss', 'Classical', 4),
(61, 'Robinson Group', 'Blues', 6),
(62, 'Holmes, Mullins and Sosa', 'Electronic', 10),
(63, 'Friedman-Gray', 'Hip-hop', 5),
(64, 'Contreras Group', 'Rap', 8),
(65, 'Wilson Group', 'Rock', 9),
(66, 'Williams Group', 'Rock', 4),
(67, 'Jones-Barnes', 'Jazz', 9),
(68, 'Mueller, Baker and Campbell', 'KPop', 4),
(69, 'Parsons, Hammond and Burgess', 'Rock', 3),
(70, 'Roberts-Hudson', 'Rap', 4),
(71, 'Parker-Gaines', 'Electronic', 6),
(72, 'Riddle-Osborn', 'Rock', 10),
(73, 'Mcmahon and Sons', 'KPop', 6),
(74, 'Ryan-Lloyd', 'Metal', 9),
(75, 'Curtis, Martin and Gross', 'Blues', 7),
(76, 'Cannon and Sons', 'Classical', 3),
(77, 'Price-Glenn', 'Jazz', 3),
(78, 'Armstrong, Cherry and Brown', 'KPop', 6),
(79, 'Bowman-Gamble', 'Blues', 7),
(80, 'Harris LLC', 'Hip-hop', 3),
(81, 'Smith LLC', 'Blues', 8),
(82, 'Evans Group', 'Electronic', 8),
(83, 'Walls Ltd', 'Classical', 6),
(84, 'Durham and Sons', 'Classical', 6),
(85, 'Mitchell, West and Arnold', 'Jazz', 8),
(86, 'Morris, Moreno and Kim', 'Rap', 4),
(87, 'Kelley-Coleman', 'Rap', 3),
(88, 'Dodson PLC', 'KPop', 6),
(89, 'Sullivan-Crawford', 'Classical', 5),
(90, 'Powell, Gomez and Massey', 'Blues', 6),
(91, 'Thompson-Graves', 'Blues', 5),
(92, 'Colon, Hines and Weiss', 'Electronic', 8),
(93, 'Walker-Reyes', 'Rap', 3),
(94, 'Cobb, Johnson and Ball', 'Classical', 3),
(95, 'Cowan Inc', 'Electronic', 9),
(96, 'Davies Group', 'KPop', 10),
(97, 'Miller-Smith', 'Hip-hop', 4),
(98, 'Price Group', 'Country', 8),
(99, 'Fox, Ryan and King', 'Rock', 3),
(100, 'Serrano, Austin and Powell', 'Classical', 6);
