INSERT INTO Artistes (Artistes_ID, Nom, Genre, Nb_Membres) VALUES
(1, 'Franco-Ruiz', 'Blues', 6),
(2, 'Walker, Moore and Roman', 'Metal', 7),
(3, 'Moore Ltd', 'Classical', 6),
(4, 'Mcdowell, Walton and Wiley', 'Jazz', 5),
(5, 'Haynes, Austin and Lawrence', 'Blues', 8),
(6, 'Deleon LLC', 'KPop', 5),
(7, 'Lee, Fitzgerald and White', 'Classical', 10),
(8, 'Charles-Roberts', 'Jazz', 9),
(9, 'Gonzales LLC', 'Country', 6),
(10, 'Brown, Gonzalez and Hendricks', 'Metal', 3),
(11, 'Parker-Underwood', 'Classical', 6),
(12, 'Cochran-Mccormick', 'Rock', 6),
(13, 'Coleman-Morris', 'Hip-hop', 7),
(14, 'Hopkins Group', 'Jazz', 10),
(15, 'Miller Ltd', 'Rock', 10),
(16, 'Yang-Powers', 'KPop', 5),
(17, 'Burns-Baker', 'Classical', 9),
(18, 'Mccoy-Harvey', 'Metal', 4),
(19, 'Olson Inc', 'Electronic', 10),
(20, 'Banks, Malone and Edwards', 'Blues', 9),
(21, 'Buchanan Inc', 'Country', 7),
(22, 'Nelson LLC', 'KPop', 5),
(23, 'Robbins, Black and Vazquez', 'Electronic', 3),
(24, 'Harrison-Mccann', 'Jazz', 5),
(25, 'Parker and Sons', 'Rap', 7),
(26, 'Harris-Fields', 'Country', 8),
(27, 'Harrington-Obrien', 'Hip-hop', 7),
(28, 'Nguyen, Neal and Molina', 'KPop', 4),
(29, 'Alexander-Crawford', 'Rock', 7),
(30, 'Wagner, Walker and Scott', 'KPop', 7),
(31, 'Meyers-Robinson', 'Electronic', 6),
(32, 'Palmer Group', 'Electronic', 4),
(33, 'Morris LLC', 'Jazz', 4),
(34, 'Murphy, Peterson and Camacho', 'Electronic', 5),
(35, 'Walker Ltd', 'Country', 7),
(36, 'Rhodes Group', 'Classical', 3),
(37, 'Sullivan LLC', 'Jazz', 10),
(38, 'Guzman, Terry and Maldonado', 'KPop', 10),
(39, 'Ewing-Brooks', 'Electronic', 4),
(40, 'Evans PLC', 'Rap', 8),
(41, 'Ross-Flores', 'Hip-hop', 5),
(42, 'Wyatt PLC', 'KPop', 6),
(43, 'Richardson PLC', 'Metal', 10),
(44, 'Horn and Sons', 'KPop', 7),
(45, 'Harris, Sanders and Fry', 'Classical', 3),
(46, 'Knapp LLC', 'Electronic', 8),
(47, 'Roberts, Morse and Brooks', 'Classical', 4),
(48, 'Cherry Inc', 'Country', 4),
(49, 'Williams, Harrison and Bishop', 'Hip-hop', 10),
(50, 'Martinez-Hernandez', 'Jazz', 3),
(51, 'Glover-Robinson', 'Jazz', 3),
(52, 'Davis Inc', 'Rap', 3),
(53, 'Jones-Jackson', 'Classical', 5),
(54, 'Trevino, Pena and Mata', 'Rock', 7),
(55, 'Harris and Sons', 'Jazz', 8),
(56, 'Campbell PLC', 'Country', 4),
(57, 'Stephens Inc', 'Rock', 9),
(58, 'Cline, Smith and Vargas', 'Hip-hop', 6),
(59, 'Smith-Mendoza', 'Jazz', 10),
(60, 'Olson Ltd', 'Metal', 5),
(61, 'Powell, White and Clark', 'Hip-hop', 3),
(62, 'Santana Group', 'KPop', 8),
(63, 'Bass-Grant', 'Jazz', 9),
(64, 'Harris, Glass and Santana', 'Blues', 10),
(65, 'Gilbert Ltd', 'Rap', 6),
(66, 'Miller-Hall', 'KPop', 8),
(67, 'Ingram, Ho and Williams', 'Blues', 4),
(68, 'Fowler and Sons', 'Hip-hop', 6),
(69, 'Gomez, Ramirez and Flowers', 'Blues', 5),
(70, 'Lopez-Smith', 'Rock', 4),
(71, 'Woodward, Freeman and Huang', 'Country', 4),
(72, 'Hoffman Group', 'Blues', 8),
(73, 'Walter, Rivera and Perry', 'Electronic', 7),
(74, 'Bennett, Webb and Ramirez', 'Metal', 4),
(75, 'Morrow Ltd', 'Rock', 3),
(76, 'Dyer Inc', 'Hip-hop', 3),
(77, 'Kim, Mcmillan and Jackson', 'Rock', 10),
(78, 'Warren Group', 'Hip-hop', 6),
(79, 'Cohen, Griffin and Stephenson', 'Classical', 6),
(80, 'Stone and Sons', 'Jazz', 10),
(81, 'Steele Inc', 'Jazz', 10),
(82, 'Wells, Griffin and Chavez', 'Hip-hop', 4),
(83, 'Wilson, Merritt and Clayton', 'Metal', 4),
(84, 'Knox PLC', 'Electronic', 6),
(85, 'Andersen-Porter', 'Country', 5),
(86, 'Murphy, Freeman and Olson', 'Metal', 10),
(87, 'Mercer LLC', 'Country', 9),
(88, 'Williams and Sons', 'Rap', 6),
(89, 'Riddle, Weaver and Burnett', 'Electronic', 9),
(90, 'Perez-Bailey', 'Rap', 5),
(91, 'Hernandez and Sons', 'Country', 3),
(92, 'Elliott and Sons', 'Blues', 9),
(93, 'Jones and Sons', 'KPop', 3),
(94, 'Ramos LLC', 'Classical', 7),
(95, 'Silva, Robinson and Jackson', 'Blues', 8),
(96, 'Murphy, Gallagher and Strong', 'Rock', 8),
(97, 'Perry-Martin', 'Blues', 3),
(98, 'Pierce, Baker and Brown', 'Country', 5),
(99, 'Taylor, Parsons and Scott', 'Rock', 4),
(100, 'King PLC', 'Classical', 10);
